name: shorm
version: 1.0.0.0
github: "laishulu/shorm"
license: MIT
author: "Lai Shulu"
maintainer: "code@mao.to"
copyright: "2024 Lai Shulu"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: A Haskell implementation of storm-ssh

flags:
  static:
    description: Enable static linking
    manual: true
    default: false

dependencies:
  - base >= 4.7 && < 5
  - directory
  - filepath
  - optparse-applicative
  - text
  - process
  - regex-base
  - regex-tdfa
  - filelock
  - time

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -optP-Wno-nonportable-include-path
  - -optl-pthread
  - -static
  - -optlc=-static

when:
  - condition: os(darwin)
    ghc-options:
      - -fPIC
      - -optl=-dead_strip

library:
  source-dirs: src
  exposed-modules:
    - Shorm.Commands
    - Shorm.Config
  other-modules:
    - Paths_shorm

executables:
  shorm:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - shorm

tests:
  shorm-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - shorm
